spring:
  profiles: develop
  datasource:
      url: jdbc:postgresql://192.168.99.100:32770/shopdb
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
---
spring:
  profiles: test
  jpa:
    show-sql: true

    properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy